// examples/vue-client/src/components/FlowUploadExample.vue
<script setup lang="ts">
import type { FlowUploadConfig } from "@uploadista/client-browser";
import { useFlowUpload } from "@uploadista/vue";
import { computed, reactive, ref, watch } from "vue";
import FilePreview from "./FilePreview.vue";
import Card from "./ui/Card.vue";
import Select from "./ui/Select.vue";

type FlowOption =
  | "optimize-flow"
  | "describe-image-flow"
  | "remove-background-flow";

const flowDescriptions: Record<
  FlowOption,
  { title: string; description: string }
> = {
  "optimize-flow": {
    title: "Image Optimization",
    description:
      "Upload an image to run through the optimization flow. Files are converted to WEBP and optimized for delivery.",
  },
  "describe-image-flow": {
    title: "Image Description",
    description:
      "Send an image through a flow that generates a rich description, useful for accessibility or content metadata.",
  },
  "remove-background-flow": {
    title: "Background Removal",
    description:
      "Process an image using the background removal flow to generate transparent-background variants.",
  },
};

const flowId = ref<FlowOption>("optimize-flow");

const flowConfig = reactive<FlowUploadConfig>({
  flowId: flowId.value,
  storageId: "local",
});

const uploadedFile = ref<File | null>(null);

const flowUpload = useFlowUpload({
  flowConfig,
  onFlowComplete: (outputs) => {
    console.log("Flow outputs:", outputs);
  },
  onError: (error) => {
    console.error("Flow upload failed:", error);
  },
});

watch(
  flowId,
  (value) => {
    flowConfig.flowId = value;
    flowUpload.reset();
    uploadedFile.value = null;
  },
  { flush: "sync" },
);

const selectedFlow = computed(() => flowDescriptions[flowId.value]);

const handleFileChange = (event: Event) => {
  const file = (event.target as HTMLInputElement).files?.[0];
  if (file) {
    uploadedFile.value = file;
    flowUpload.upload(file);
  }
};
</script>

<template>
  <Card class="p-8 space-y-8">
    <header class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
      <div class="space-y-2">
        <h2 class="text-3xl font-bold text-gray-900">
          Flow Upload — {{ selectedFlow.title }}
        </h2>
        <p class="text-gray-600 leading-relaxed">
          {{ selectedFlow.description }}
        </p>
      </div>
      <div class="w-full md:w-72">
        <label
          class="block text-xs font-semibold uppercase tracking-wide text-gray-600 mb-2"
          for="flow-selector"
        >
          Flow
        </label>
        <Select
          id="flow-selector"
          v-model="flowId"
          :options="[
            { value: 'optimize-flow', label: 'Optimize Image' },
            { value: 'describe-image-flow', label: 'Describe Image' },
            { value: 'remove-background-flow', label: 'Remove Background' },
          ]"
        />
      </div>
    </header>

    <section class="space-y-6">
      <div>
        <label
          class="block text-sm font-semibold text-gray-700 mb-2 uppercase tracking-wide"
          for="flow-upload-input"
        >
          Choose Image File
        </label>
        <input
          id="flow-upload-input"
          type="file"
          accept="image/*"
          :disabled="flowUpload.isUploading.value"
          class="block w-full text-gray-700 file:mr-4 file:py-3 file:px-6 file:rounded-xl file:border-0 file:bg-gradient-to-r file:from-indigo-600 file:to-purple-600 file:text-white file:font-semibold file:cursor-pointer hover:file:from-indigo-700 hover:file:to-purple-700 file:transition-all file:shadow-md border-2 border-gray-200 rounded-xl focus:outline-none focus:border-indigo-500 disabled:opacity-50 disabled:cursor-not-allowed"
          @change="handleFileChange"
        />
      </div>

      <div v-if="flowUpload.state.value.jobId" class="rounded-xl border border-blue-100 bg-blue-50 p-4">
        <p class="text-sm font-semibold text-blue-700 mb-1">Job ID</p>
        <code class="text-xs font-mono text-blue-900 break-all">{{
          flowUpload.state.value.jobId
        }}</code>
      </div>

      <div
        v-if="flowUpload.isUploadingFile.value"
        class="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl p-6 border border-indigo-100 space-y-4"
      >
        <div class="grid grid-cols-2 gap-4">
          <div class="bg-white rounded-xl p-4 shadow-sm">
            <p class="text-sm font-semibold text-gray-500 mb-2">Upload Status</p>
            <p class="text-lg font-semibold capitalize text-indigo-700">
              {{ flowUpload.state.value.status }}
            </p>
          </div>
          <div class="bg-white rounded-xl p-4 shadow-sm">
            <p class="text-sm font-semibold text-gray-500 mb-2">Progress</p>
            <p class="text-2xl font-bold text-gray-900">
              {{ flowUpload.state.value.progress }}%
            </p>
          </div>
        </div>

        <div class="relative h-3 bg-gray-200 rounded-full overflow-hidden">
          <div
            class="absolute inset-y-0 left-0 progress-bar-gradient transition-all duration-300 ease-out"
            :style="{ width: `${flowUpload.state.value.progress}%` }"
          />
        </div>

        <button
          type="button"
          class="w-full px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
          :disabled="!flowUpload.isUploading.value"
          @click="flowUpload.abort"
        >
          Abort Upload
        </button>
      </div>

      <div
        v-if="flowUpload.isProcessing.value"
        class="rounded-2xl border border-purple-200 bg-purple-50 p-6 space-y-4"
      >
        <p class="text-sm font-semibold text-purple-700 uppercase tracking-wide">
          Processing Flow
        </p>
        <p class="text-base text-purple-800">
          {{
            flowUpload.state.value.currentNodeName
              ? `Current node: ${flowUpload.state.value.currentNodeName}`
              : "Running nodes..."
          }}
        </p>
        <div class="w-full bg-purple-200 rounded-full h-3 overflow-hidden">
          <div class="bg-purple-500 h-3 rounded-full animate-pulse w-full" />
        </div>
      </div>

      <div
        v-if="flowUpload.state.value.status === 'success'"
        class="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-6 border border-green-200 space-y-4"
      >
        <div class="flex items-start gap-3">
          <div
            class="flex-shrink-0 w-10 h-10 bg-green-500 rounded-full flex items-center justify-center"
          >
            <svg
              class="w-6 h-6 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M5 13l4 4L19 7"
              />
            </svg>
          </div>
          <div class="flex-1">
            <h3 class="text-lg font-bold text-green-900 mb-1">
              Flow Complete
            </h3>
            <p class="text-green-700">
              The file finished processing. Inspect the outputs below.
            </p>
          </div>
        </div>

        <FilePreview
          v-if="uploadedFile"
          :file="uploadedFile"
          :result="flowUpload.state.value.result ?? undefined"
        />

        <details
          v-if="flowUpload.state.value.flowOutputs"
          class="bg-white rounded-xl border border-green-200"
        >
          <summary
            class="px-4 py-3 cursor-pointer font-semibold text-gray-700 hover:text-gray-900"
          >
            Flow Outputs
          </summary>
          <pre class="px-4 pb-4 text-sm text-gray-800 overflow-auto font-mono">
{{ JSON.stringify(flowUpload.state.value.flowOutputs, null, 2) }}
          </pre>
        </details>

        <button
          type="button"
          class="w-full px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md"
          @click="flowUpload.reset"
        >
          Upload Another File
        </button>
      </div>

      <div
        v-if="flowUpload.state.value.status === 'error' && flowUpload.state.value.error"
        class="bg-gradient-to-br from-red-50 to-rose-50 rounded-2xl p-6 border border-red-200 space-y-4"
      >
        <div class="flex items-start gap-3">
          <div
            class="flex-shrink-0 w-10 h-10 bg-red-500 rounded-full flex items-center justify-center"
          >
            <svg
              class="w-6 h-6 text-white"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </div>
          <div class="flex-1">
            <h3 class="text-lg font-bold text-red-900 mb-1">
              Flow Failed
            </h3>
            <p class="text-red-700">{{ flowUpload.state.value.error.message }}</p>
          </div>
        </div>

        <button
          type="button"
          class="w-full px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md"
          @click="flowUpload.reset"
        >
          Try Again
        </button>
      </div>
    </section>
  </Card>
</template>

// examples/next-cloud-client/src/components/FlowUploadExample.tsx
import type { UploadFile } from "@uploadista/core/types";
import { Flow } from "@uploadista/react";
import { useState } from "react";
import { FilePreview } from "./FilePreview";

function FlowUploadContent() {
  const [uploadedFile, setUploadedFile] = useState<File | null>(null);

  return (
    <div className="max-w-3xl mx-auto">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-3">
          Flow Upload with Image Optimization
        </h2>
        <p className="text-gray-600 leading-relaxed">
          Upload an image file through a processing flow. This example uses the
          "optimize-flow" which optimizes and converts images to JPEG format at
          80% quality.
        </p>
      </div>

      {/* Using the new Flow compound component */}
      <Flow
        flowId="optimize-flow"
        storageId="local"
        onSuccess={(result) => {
          console.log("Flow upload complete:", result);
        }}
        onError={(error) => {
          console.error("Flow upload failed:", error);
        }}
      >
        {/* Simple DropZone for single file upload */}
        <Flow.DropZone accept="image/*">
          {({
            isDragging,
            progress,
            status,
            getRootProps,
            getInputProps,
            openFilePicker,
          }) => {
            const isUploading = status === "uploading";
            const isProcessing = status === "processing";
            const isBusy = isUploading || isProcessing;

            return (
              <div className="space-y-6">
                {/* File Input */}
                <div>
                  <label
                    htmlFor="flow-file-input"
                    className="block text-sm font-semibold text-gray-700 mb-2 uppercase tracking-wide"
                  >
                    Choose Image File
                  </label>
                  <div
                    {...getRootProps()}
                    className={`block w-full text-gray-700 border-2 rounded-xl focus:outline-none transition-colors cursor-pointer ${
                      isDragging
                        ? "border-indigo-500 bg-indigo-50"
                        : "border-gray-200 hover:border-indigo-400"
                    } ${isBusy ? "opacity-50 cursor-not-allowed" : ""}`}
                    onClick={() => !isBusy && openFilePicker()}
                    onKeyDown={(e) => {
                      if ((e.key === "Enter" || e.key === " ") && !isBusy) {
                        e.preventDefault();
                        openFilePicker();
                      }
                    }}
                    role="button"
                    tabIndex={0}
                  >
                    <input
                      {...getInputProps()}
                      id="flow-file-input"
                      onChange={(e) => {
                        const file = e.target.files?.[0];
                        if (file) {
                          setUploadedFile(file);
                        }
                      }}
                    />
                    <div className="py-3 px-6 text-center">
                      {isDragging ? (
                        <span className="text-indigo-600 font-semibold">
                          Drop file here...
                        </span>
                      ) : (
                        <span>
                          Click to select or drag & drop an image file
                        </span>
                      )}
                    </div>
                  </div>
                </div>

                {/* Upload Progress Section */}
                {isUploading && (
                  <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-100">
                    <div className="grid grid-cols-2 gap-4 mb-6">
                      <div className="bg-white rounded-xl p-4 shadow-sm">
                        <div className="text-sm font-semibold text-gray-500 mb-2">
                          Status
                        </div>
                        <div>
                          <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-blue-100 text-blue-700">
                            Uploading
                          </span>
                        </div>
                      </div>
                      <div className="bg-white rounded-xl p-4 shadow-sm">
                        <div className="text-sm font-semibold text-gray-500 mb-2">
                          Progress
                        </div>
                        <div className="text-2xl font-bold text-gray-900">
                          {progress}%
                        </div>
                      </div>
                    </div>

                    {/* Upload Progress Bar */}
                    <div className="relative h-3 bg-gray-200 rounded-full overflow-hidden mb-4">
                      <div
                        className="absolute inset-y-0 left-0 progress-bar-gradient transition-all duration-300 ease-out"
                        style={{ width: `${progress}%` }}
                      />
                    </div>

                    {/* Abort Button */}
                    <Flow.Cancel className="w-full px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md">
                      Abort Upload
                    </Flow.Cancel>
                  </div>
                )}

                {/* Flow Processing Section */}
                <Flow.Status>
                  {({ status: flowStatus, currentNodeName }) =>
                    flowStatus === "processing" && (
                      <div className="bg-gradient-to-br from-purple-50 to-indigo-50 rounded-2xl p-6 border border-purple-100">
                        <div className="bg-white rounded-xl p-4 shadow-sm mb-4">
                          <div className="text-sm font-semibold text-gray-500 mb-2">
                            Status
                          </div>
                          <div>
                            <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-purple-100 text-purple-700">
                              Processing Flow
                            </span>
                          </div>
                        </div>

                        {/* Processing Animation */}
                        <div className="w-full bg-gray-200 rounded-full h-3 mb-2 overflow-hidden">
                          <div className="bg-purple-600 h-3 rounded-full animate-pulse w-full" />
                        </div>

                        {/* Current Node Info */}
                        <p className="text-sm text-gray-700 mb-4">
                          {currentNodeName
                            ? `Processing: ${currentNodeName}`
                            : "Processing flow..."}
                        </p>

                        {/* Abort Button */}
                        <Flow.Cancel className="w-full px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md">
                          Abort Flow
                        </Flow.Cancel>
                      </div>
                    )
                  }
                </Flow.Status>

                {/* Success Message */}
                <Flow.Status>
                  {({ status: flowStatus, flowOutputs }) =>
                    flowStatus === "success" && (
                      <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-6 border border-green-200">
                        <div className="flex items-start gap-3 mb-4">
                          <div className="flex-shrink-0 w-10 h-10 bg-green-500 rounded-full flex items-center justify-center">
                            <svg
                              className="w-6 h-6 text-white"
                              fill="none"
                              viewBox="0 0 24 24"
                              stroke="currentColor"
                              aria-hidden="true"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M5 13l4 4L19 7"
                              />
                            </svg>
                          </div>
                          <div className="flex-1">
                            <h3 className="text-lg font-bold text-green-900 mb-1">
                              Flow Complete!
                            </h3>
                            <p className="text-green-700">
                              Image uploaded and optimized successfully.
                            </p>
                          </div>
                        </div>
                        {/* File Preview */}
                        {uploadedFile && flowOutputs && flowOutputs.length > 0 && (
                          <FilePreview
                            file={uploadedFile}
                            result={
                              flowOutputs.find(
                                (o) => o.nodeType === "storage-output-v1",
                              )?.data as UploadFile | undefined
                            }
                            className="mb-4"
                          />
                        )}

                        {flowOutputs && flowOutputs.length > 0 && (
                          <details className="bg-white rounded-xl border border-green-200">
                            <summary className="px-4 py-3 cursor-pointer font-semibold text-gray-700 hover:text-gray-900">
                              View Flow Result Details
                            </summary>
                            <pre className="px-4 pb-4 text-sm text-gray-800 overflow-auto font-mono">
                              {JSON.stringify(flowOutputs, null, 2)}
                            </pre>
                          </details>
                        )}
                        <Flow.Reset className="mt-4 w-full px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md">
                          Upload Another Image
                        </Flow.Reset>
                      </div>
                    )
                  }
                </Flow.Status>

                {/* Error Message */}
                <Flow.Error>
                  {({ error }) =>
                    error && (
                      <div className="bg-gradient-to-br from-red-50 to-rose-50 rounded-2xl p-6 border border-red-200">
                        <div className="flex items-start gap-3 mb-4">
                          <div className="flex-shrink-0 w-10 h-10 bg-red-500 rounded-full flex items-center justify-center">
                            <svg
                              className="w-6 h-6 text-white"
                              fill="none"
                              viewBox="0 0 24 24"
                              stroke="currentColor"
                              aria-hidden="true"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M6 18L18 6M6 6l12 12"
                              />
                            </svg>
                          </div>
                          <div className="flex-1">
                            <h3 className="text-lg font-bold text-red-900 mb-1">
                              Flow Failed
                            </h3>
                            <p className="text-red-700">{error.message}</p>
                          </div>
                        </div>
                        <Flow.Reset className="w-full px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md">
                          Try Another File
                        </Flow.Reset>
                      </div>
                    )
                  }
                </Flow.Error>
              </div>
            );
          }}
        </Flow.DropZone>
      </Flow>
    </div>
  );
}

export function FlowUploadExample() {
  return <FlowUploadContent />;
}
