// packages/clients/react/src/components/flow-upload-zone.tsx
import type {
  FlowUploadConfig,
  FlowUploadOptions,
} from "@uploadista/client-browser";
import type { ReactNode } from "react";
import { type UseDragDropReturn, useDragDrop } from "../hooks/use-drag-drop";
import {
  type UseFlowUploadReturn,
  useFlowUpload,
} from "../hooks/use-flow-upload";

export interface FlowUploadZoneRenderProps {
  /**
   * Drag and drop state and handlers
   */
  dragDrop: UseDragDropReturn;

  /**
   * Flow upload functionality
   */
  flowUpload: UseFlowUploadReturn;

  /**
   * Whether the zone is currently active (dragging or uploading)
   */
  isActive: boolean;

  /**
   * Open file picker
   */
  openFilePicker: () => void;

  /**
   * Props to spread on the drop zone element
   */
  getRootProps: () => {
    onDragEnter: (e: React.DragEvent) => void;
    onDragOver: (e: React.DragEvent) => void;
    onDragLeave: (e: React.DragEvent) => void;
    onDrop: (e: React.DragEvent) => void;
  };

  /**
   * Props to spread on the file input element
   */
  getInputProps: () => React.InputHTMLAttributes<HTMLInputElement>;
}

export interface FlowUploadZoneProps {
  /**
   * Flow configuration
   */
  flowConfig: FlowUploadConfig;

  /**
   * Upload options
   */
  options?: Omit<FlowUploadOptions, "flowConfig">;

  /**
   * Accepted file types (e.g., "image/*", ".pdf", etc.)
   */
  accept?: string;

  /**
   * Whether to allow multiple files (uses multi-upload internally)
   */
  multiple?: boolean;

  /**
   * Render function for the drop zone
   */
  children: (props: FlowUploadZoneRenderProps) => ReactNode;
}

/**
 * Flow upload zone component with drag-and-drop support
 *
 * @example
 * ```tsx
 * <FlowUploadZone
 *   client={client}
 *   flowConfig={{
 *     flowId: "my-upload-flow",
 *     storageId: "my-storage",
 *   }}
 *   accept="image/*"
 * >
 *   {({ isDragging, isUploading, state, getRootProps, getInputProps, openFilePicker }) => (
 *     <div {...getRootProps()}>
 *       <input {...getInputProps()} />
 *
 *       {isDragging && <p>Drop files here...</p>}
 *       {!isDragging && !isUploading && (
 *         <button onClick={openFilePicker}>Choose Files</button>
 *       )}
 *       {isUploading && (
 *         <div>
 *           <progress value={state.progress} max={100} />
 *           <p>{state.progress}%</p>
 *         </div>
 *       )}
 *       {state.status === "success" && <p>Upload complete!</p>}
 *       {state.status === "error" && <p>Error: {state.error?.message}</p>}
 *     </div>
 *   )}
 * </FlowUploadZone>
 * ```
 */
export function FlowUploadZone({
  flowConfig,
  options,
  accept,
  multiple = false,
  children,
}: FlowUploadZoneProps) {
  // Hook automatically subscribes to events through context
  const flowUpload = useFlowUpload({
    ...options,
    flowConfig,
  });

  const dragDrop = useDragDrop({
    onFilesReceived: (files: File[]) => {
      const file = files[0];
      if (file) {
        flowUpload.upload(file);
      }
    },
    accept: accept ? [accept] : undefined,
    multiple,
  });

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    const file = files?.[0];
    if (file) {
      flowUpload.upload(file);
    }
  };

  // Determine active state
  const isActive = dragDrop.state.isDragging || dragDrop.state.isOver;

  return (
    <>
      {children({
        flowUpload,
        dragDrop,
        isActive,
        openFilePicker: dragDrop.openFilePicker,
        getRootProps: () => dragDrop.dragHandlers,
        getInputProps: () => ({
          ...dragDrop.inputProps,
          onChange: handleFileChange,
        }),
      })}
    </>
  );
}

export interface SimpleFlowUploadZoneProps {
  /**
   * Flow configuration
   */
  flowConfig: FlowUploadConfig;

  /**
   * Upload options
   */
  options?: Omit<FlowUploadOptions, "flowConfig">;

  /**
   * Accepted file types
   */
  accept?: string;

  /**
   * CSS class for the container
   */
  className?: string;

  /**
   * Custom drag overlay text
   */
  dragText?: string;

  /**
   * Custom idle text
   */
  idleText?: string;
}

/**
 * Simple pre-styled flow upload zone component
 *
 * @example
 * ```tsx
 * <SimpleFlowUploadZone
 
 *   flowConfig={{
 *     flowId: "my-upload-flow",
 *     inputNodeId: "upload-node",
 *     storageId: "my-storage",
 *   }}
 *   accept="image/*"
 *   onSuccess={(result) => console.log("Uploaded:", result)}
 * />
 * ```
 */
export function SimpleFlowUploadZone({
  flowConfig,
  options,
  accept,
  className = "",
  dragText = "Drop files here",
  idleText = "Drag & drop files or click to browse",
}: SimpleFlowUploadZoneProps) {
  return (
    <FlowUploadZone flowConfig={flowConfig} options={options} accept={accept}>
      {({
        dragDrop,
        flowUpload,
        getRootProps,
        getInputProps,
        openFilePicker,
      }) => (
        <div
          {...getRootProps()}
          className={className}
          style={{
            border: "2px dashed #ccc",
            borderRadius: "8px",
            padding: "32px",
            textAlign: "center",
            cursor: "pointer",
            backgroundColor: dragDrop.state.isDragging
              ? "#f0f0f0"
              : "transparent",
            transition: "background-color 0.2s",
          }}
        >
          <input {...getInputProps()} />

          {dragDrop.state.isDragging && <p style={{ margin: 0 }}>{dragText}</p>}

          {!dragDrop.state.isDragging &&
            !flowUpload.isUploading &&
            flowUpload.state.status === "idle" && (
              <div>
                <p style={{ margin: "0 0 16px 0" }}>{idleText}</p>
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    openFilePicker();
                  }}
                  style={{
                    padding: "8px 16px",
                    borderRadius: "4px",
                    border: "1px solid #ccc",
                    backgroundColor: "#fff",
                    cursor: "pointer",
                  }}
                >
                  Choose Files
                </button>
              </div>
            )}

          {flowUpload.isUploading && (
            <div>
              <progress
                value={flowUpload.state.progress}
                max={100}
                style={{ width: "100%", height: "8px" }}
              />
              <p style={{ margin: "8px 0 0 0" }}>
                {flowUpload.state.progress}%
              </p>
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  // abort() will be passed from parent
                }}
                style={{
                  marginTop: "8px",
                  padding: "4px 12px",
                  borderRadius: "4px",
                  border: "1px solid #ccc",
                  backgroundColor: "#fff",
                  cursor: "pointer",
                }}
              >
                Cancel
              </button>
            </div>
          )}

          {flowUpload.state.status === "success" && (
            <div>
              <p style={{ margin: 0, color: "green" }}>✓ Upload complete!</p>
            </div>
          )}

          {flowUpload.state.status === "error" && (
            <div>
              <p style={{ margin: 0, color: "red" }}>
                ✗ Error: {flowUpload.state.error?.message}
              </p>
            </div>
          )}
        </div>
      )}
    </FlowUploadZone>
  );
}

// packages/clients/vue/src/components/FlowUploadZone.vue
<script setup lang="ts">
/**
 * FlowUploadZone - Upload zone with flow processing pipeline
 *
 * Specialized upload component that uploads files through a flow pipeline for processing.
 * Supports drag-and-drop and file picker with flow configuration. Emits events for flow
 * completion, errors, and upload status changes.
 *
 * @component
 * @example
 * // Upload images through image processing flow
 * <FlowUploadZone
 *   :flow-config="{ flowId: 'image-processor' }"
 *   accept="image/*"
 *   @upload-complete="handleFlowResult"
 *   @upload-error="handleError"
 * />
 *
 * @example
 * // With custom slot content
 * <FlowUploadZone
 *   :flow-config="{ flowId: 'image-processor' }"
 *   @upload-complete="handleResult"
 * >
 *   <template #default="{ isDragging, isProcessing, progress }">
 *     <div :class="{ processing: isProcessing }">
 *       <p v-if="isProcessing">Processing... {{ progress }}%</p>
 *       <p v-else-if="isDragging">Drop file here</p>
 *       <p v-else>Drag file here for processing</p>
 *     </div>
 *   </template>
 * </FlowUploadZone>
 *
 * @emits upload-complete - Flow processing completed with results
 * @emits upload-error - Upload or processing failed
 * @emits upload-start - File upload started
 * @emits validation-error - File validation failed
 */
import type {
  FlowUploadConfig,
  FlowUploadOptions,
} from "@uploadista/client-browser";
import { computed, ref } from "vue";
import { useDragDrop, useFlowUpload } from "../composables";

/**
 * Props for the FlowUploadZone component
 * @property {FlowUploadConfig} flowConfig - Flow configuration with flowId
 * @property {FlowUploadOptions} options - Additional flow upload options
 * @property {string} accept - Accepted file types (single MIME type or extension string)
 * @property {boolean} multiple - Allow multiple files (default: false, flow uploads are single-file)
 * @property {boolean} disabled - Disable the upload zone (default: false)
 * @property {number} maxFileSize - Maximum file size in bytes
 */
export interface FlowUploadZoneProps {
  /**
   * Flow configuration
   */
  flowConfig: FlowUploadConfig;

  /**
   * Additional flow upload options
   */
  options?: Omit<FlowUploadOptions, "flowConfig">;

  /**
   * Accepted file types (single MIME type or extension string)
   */
  accept?: string;

  /**
   * Whether to allow multiple files (currently only single file supported for flow uploads)
   */
  multiple?: boolean;

  /**
   * Whether the upload zone is disabled
   */
  disabled?: boolean;

  /**
   * Maximum file size in bytes
   */
  maxFileSize?: number;
}

const props = withDefaults(defineProps<FlowUploadZoneProps>(), {
  multiple: false,
  disabled: false,
});

// biome-ignore lint/suspicious/noExplicitAny: Flow result can be any type
const emit = defineEmits<{
  // biome-ignore lint/suspicious/noExplicitAny: Flow result can be any type
  "upload-complete": [result: any];
  "upload-error": [error: Error];
  "upload-start": [file: File];
  "validation-error": [errors: string[]];
}>();

// biome-ignore lint/suspicious/noExplicitAny: Vue slot definition requires any
defineSlots<{
  // biome-ignore lint/suspicious/noExplicitAny: Vue slot definition requires any
  default(props: {
    isDragging: boolean;
    isOver: boolean;
    isUploading: boolean;
    isProcessing: boolean;
    progress: number;
    status: string;
    errors: string[];
    openFilePicker: () => void;
  }): any;
}>();

// Initialize flow upload
const flowUpload = useFlowUpload({
  ...props.options,
  flowConfig: props.flowConfig,
  onFlowComplete: (outputs) => {
    emit("upload-complete", outputs);
    props.options?.onFlowComplete?.(outputs);
  },
  onError: (error) => {
    emit("upload-error", error);
    props.options?.onError?.(error);
  },
});

// Handle files received from drag-drop or file picker
const handleFilesReceived = (files: File[]) => {
  const file = files[0];
  if (file) {
    emit("upload-start", file);
    flowUpload.upload(file);
  }
};

// Handle validation errors
const handleValidationError = (errors: string[]) => {
  emit("validation-error", errors);
};

// Initialize drag-drop
const dragDrop = useDragDrop({
  accept: props.accept ? [props.accept] : undefined,
  multiple: props.multiple,
  maxFileSize: props.maxFileSize,
  onFilesReceived: handleFilesReceived,
  onValidationError: handleValidationError,
});

// File input ref
const fileInputRef = ref<HTMLInputElement>();

// Open file picker
// biome-ignore lint/correctness/noUnusedVariables: Used in slot templates
const openFilePicker = () => {
  if (!props.disabled) {
    fileInputRef.value?.click();
  }
};

// Computed states
// biome-ignore lint/correctness/noUnusedVariables: Used in slot templates
const isActive = computed(
  () => dragDrop.state.value.isDragging || dragDrop.state.value.isOver,
);
</script>

<template>
  <div
    class="flow-upload-zone"
    :class="{
      'flow-upload-zone--active': isActive,
      'flow-upload-zone--disabled': disabled,
      'flow-upload-zone--uploading': flowUpload.isUploading.value
    }"
    @dragenter="!disabled && dragDrop.onDragEnter"
    @dragover="!disabled && dragDrop.onDragOver"
    @dragleave="!disabled && dragDrop.onDragLeave"
    @drop="!disabled && dragDrop.onDrop"
    @click="openFilePicker"
    role="button"
    :tabindex="disabled ? -1 : 0"
    :aria-disabled="disabled"
    aria-label="Upload file with flow processing"
    @keydown.enter="openFilePicker"
    @keydown.space.prevent="openFilePicker"
  >
    <slot
      :is-dragging="dragDrop.state.value.isDragging"
      :is-over="dragDrop.state.value.isOver"
      :is-uploading="flowUpload.isUploading.value"
      :is-processing="flowUpload.isProcessing.value"
      :progress="flowUpload.state.value.progress"
      :status="flowUpload.state.value.status"
      :errors="[...dragDrop.state.value.errors]"
      :open-file-picker="openFilePicker"
    >
      <!-- Default slot content -->
      <div class="flow-upload-zone__content">
        <p v-if="dragDrop.state.value.isDragging">Drop file here...</p>
        <p v-else-if="flowUpload.isUploading.value">
          Uploading... {{ flowUpload.state.value.progress }}%
        </p>
        <p v-else-if="flowUpload.isProcessing.value">
          Processing...
          <span v-if="flowUpload.state.value.currentNodeName">
            ({{ flowUpload.state.value.currentNodeName }})
          </span>
        </p>
        <p v-else-if="flowUpload.state.value.status === 'success'">Upload complete!</p>
        <p v-else-if="flowUpload.state.value.status === 'error'" class="flow-upload-zone__error">
          Error: {{ flowUpload.state.value.error?.message }}
        </p>
        <p v-else>Drag a file here or click to select</p>

        <div v-if="flowUpload.isUploading.value" class="flow-upload-zone__progress">
          <div class="flow-upload-zone__progress-bar">
            <div
              class="flow-upload-zone__progress-fill"
              :style="{ width: `${flowUpload.state.value.progress}%` }"
            />
          </div>
        </div>

        <div v-if="dragDrop.state.value.errors.length > 0" class="flow-upload-zone__errors">
          <p v-for="(error, index) in dragDrop.state.value.errors" :key="index">
            {{ error }}
          </p>
        </div>
      </div>
    </slot>

    <input
      ref="fileInputRef"
      type="file"
      :multiple="dragDrop.inputProps.value.multiple"
      :accept="dragDrop.inputProps.value.accept"
      :disabled="disabled"
      @change="dragDrop.onInputChange"
      style="display: none"
      aria-hidden="true"
    />
  </div>
</template>

<style scoped>
.flow-upload-zone {
  cursor: pointer;
  user-select: none;
}

.flow-upload-zone--disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

.flow-upload-zone--uploading {
  pointer-events: none;
}

.flow-upload-zone__content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
}

.flow-upload-zone__error {
  color: #dc3545;
}

.flow-upload-zone__progress {
  width: 100%;
  max-width: 300px;
  margin-top: 0.5rem;
}

.flow-upload-zone__progress-bar {
  width: 100%;
  height: 0.5rem;
  background-color: #e0e0e0;
  border-radius: 0.25rem;
  overflow: hidden;
}

.flow-upload-zone__progress-fill {
  height: 100%;
  background-color: #007bff;
  transition: width 0.2s ease;
}

.flow-upload-zone__errors {
  margin-top: 0.5rem;
  color: #dc3545;
  font-size: 0.875rem;
}

.flow-upload-zone__errors p {
  margin: 0.25rem 0;
}
</style>
