// packages/clients/react/src/components/upload-list.tsx
import type React from "react";
import type {
  UploadItem,
  UseMultiUploadReturn,
} from "../hooks/use-multi-upload";
import type { UploadStatus } from "../hooks/use-upload";

export interface UploadListRenderProps {
  /**
   * All upload items
   */
  items: UploadItem[];

  /**
   * Items filtered by status
   */
  itemsByStatus: {
    idle: UploadItem[];
    uploading: UploadItem[];
    success: UploadItem[];
    error: UploadItem[];
    aborted: UploadItem[];
  };

  /**
   * Multi-upload state and controls
   */
  multiUpload: UseMultiUploadReturn;

  /**
   * Helper functions for item management
   */
  actions: {
    removeItem: (id: string) => void;
    retryItem: (item: UploadItem) => void;
    abortItem: (item: UploadItem) => void;
    startItem: (item: UploadItem) => void;
  };
}

export interface UploadListProps {
  /**
   * Multi-upload instance from useMultiUpload hook
   */
  multiUpload: UseMultiUploadReturn;

  /**
   * Optional filter for which items to display
   */
  filter?: (item: UploadItem) => boolean;

  /**
   * Optional sorting function for items
   */
  sortBy?: (a: UploadItem, b: UploadItem) => number;

  /**
   * Render prop that receives upload list state and actions
   */
  children: (props: UploadListRenderProps) => React.ReactNode;
}

/**
 * Headless upload list component that provides flexible rendering for upload items.
 * Uses render props pattern to give full control over how upload items are displayed.
 *
 * @param props - Upload list configuration and render prop
 * @returns Rendered upload list using the provided render prop
 *
 * @example
 * ```tsx
 * // Basic upload list with progress bars
 * <UploadList multiUpload={multiUpload}>
 *   {({ items, actions }) => (
 *     <div>
 *       <h3>Upload Queue ({items.length} files)</h3>
 *       {items.map((item) => (
 *         <div key={item.id} style={{
 *           padding: '1rem',
 *           border: '1px solid #ccc',
 *           marginBottom: '0.5rem',
 *           borderRadius: '4px'
 *         }}>
 *           <div style={{ display: 'flex', justifyContent: 'space-between' }}>
 *             <span>{item.file.name}</span>
 *             <span>{item.state.status}</span>
 *           </div>
 *
 *           {item.state.status === 'uploading' && (
 *             <div>
 *               <progress value={item.state.progress} max={100} />
 *               <span>{item.state.progress}%</span>
 *               <button onClick={() => actions.abortItem(item)}>Cancel</button>
 *             </div>
 *           )}
 *
 *           {item.state.status === 'error' && (
 *             <div>
 *               <p style={{ color: 'red' }}>Error: {item.state.error?.message}</p>
 *               <button onClick={() => actions.retryItem(item)}>Retry</button>
 *               <button onClick={() => actions.removeItem(item.id)}>Remove</button>
 *             </div>
 *           )}
 *
 *           {item.state.status === 'success' && (
 *             <div>
 *               <p style={{ color: 'green' }}>✓ Uploaded successfully</p>
 *               <button onClick={() => actions.removeItem(item.id)}>Remove</button>
 *             </div>
 *           )}
 *
 *           {item.state.status === 'idle' && (
 *             <div>
 *               <button onClick={() => actions.startItem(item)}>Start Upload</button>
 *               <button onClick={() => actions.removeItem(item.id)}>Remove</button>
 *             </div>
 *           )}
 *         </div>
 *       ))}
 *     </div>
 *   )}
 * </UploadList>
 *
 * // Upload list with status filtering and sorting
 * <UploadList
 *   multiUpload={multiUpload}
 *   filter={(item) => item.state.status !== 'success'} // Hide successful uploads
 *   sortBy={(a, b) => {
 *     // Sort by status priority, then by filename
 *     const statusPriority = { error: 0, uploading: 1, idle: 2, success: 3, aborted: 4 };
 *     const aPriority = statusPriority[a.state.status];
 *     const bPriority = statusPriority[b.state.status];
 *
 *     if (aPriority !== bPriority) {
 *       return aPriority - bPriority;
 *     }
 *
 *     return a.file.name.localeCompare(b.file.name);
 *   }}
 * >
 *   {({ items, itemsByStatus, multiUpload, actions }) => (
 *     <div>
 *       {itemsByStatus.error.length > 0 && (
 *         <div>
 *           <h4 style={{ color: 'red' }}>Failed Uploads ({itemsByStatus.error.length})</h4>
 *           {itemsByStatus.error.map((item) => (
 *             <UploadListItem key={item.id} item={item} actions={actions} />
 *           ))}
 *         </div>
 *       )}
 *
 *       {itemsByStatus.uploading.length > 0 && (
 *         <div>
 *           <h4>Uploading ({itemsByStatus.uploading.length})</h4>
 *           {itemsByStatus.uploading.map((item) => (
 *             <UploadListItem key={item.id} item={item} actions={actions} />
 *           ))}
 *         </div>
 *       )}
 *
 *       {itemsByStatus.idle.length > 0 && (
 *         <div>
 *           <h4>Pending ({itemsByStatus.idle.length})</h4>
 *           {itemsByStatus.idle.map((item) => (
 *             <UploadListItem key={item.id} item={item} actions={actions} />
 *           ))}
 *         </div>
 *       )}
 *     </div>
 *   )}
 * </UploadList>
 * ```
 */
export function UploadList({
  multiUpload,
  filter,
  sortBy,
  children,
}: UploadListProps) {
  // Apply filtering
  let items = multiUpload.items;
  if (filter) {
    items = items.filter(filter);
  }

  // Apply sorting
  if (sortBy) {
    items = [...items].sort(sortBy);
  }

  // Group items by status
  const itemsByStatus = {
    idle: items.filter((item) => item.state.status === "idle"),
    uploading: items.filter((item) => item.state.status === "uploading"),
    success: items.filter((item) => item.state.status === "success"),
    error: items.filter((item) => item.state.status === "error"),
    aborted: items.filter((item) => item.state.status === "aborted"),
  };

  // Create action helpers
  const actions = {
    removeItem: (id: string) => {
      multiUpload.removeItem(id);
    },
    retryItem: (_item: UploadItem) => {
      // Retry failed uploads using multiUpload method
      multiUpload.retryFailed();
    },
    abortItem: (item: UploadItem) => {
      // Remove the item to effectively abort it
      multiUpload.removeItem(item.id);
    },
    startItem: (_item: UploadItem) => {
      // Start all pending uploads
      multiUpload.startAll();
    },
  };

  // Create render props object
  const renderProps: UploadListRenderProps = {
    items,
    itemsByStatus,
    multiUpload,
    actions,
  };

  return <>{children(renderProps)}</>;
}

/**
 * Simple upload list item component for quick prototyping.
 * Provides a basic UI for upload items with common actions.
 *
 * @example
 * ```tsx
 * <UploadList multiUpload={multiUpload}>
 *   {({ items, actions }) => (
 *     <div>
 *       {items.map((item) => (
 *         <SimpleUploadListItem key={item.id} item={item} actions={actions} />
 *       ))}
 *     </div>
 *   )}
 * </UploadList>
 * ```
 */
export interface SimpleUploadListItemProps {
  /**
   * The upload item to render
   */
  item: UploadItem;

  /**
   * Actions from UploadList render props
   */
  actions: UploadListRenderProps["actions"];

  /**
   * Additional CSS class name
   */
  className?: string;

  /**
   * Inline styles
   */
  style?: React.CSSProperties;

  /**
   * Whether to show detailed information (file size, speed, etc.)
   */
  showDetails?: boolean;
}

export function SimpleUploadListItem({
  item,
  actions,
  className = "",
  style = {},
  showDetails = true,
}: SimpleUploadListItemProps) {
  const getStatusColor = (status: UploadStatus) => {
    switch (status) {
      case "idle":
        return "#6c757d";
      case "uploading":
        return "#007bff";
      case "success":
        return "#28a745";
      case "error":
        return "#dc3545";
      case "aborted":
        return "#6c757d";
      default:
        return "#6c757d";
    }
  };

  const getStatusIcon = (status: UploadStatus) => {
    switch (status) {
      case "idle":
        return "⏳";
      case "uploading":
        return "📤";
      case "success":
        return "✅";
      case "error":
        return "❌";
      case "aborted":
        return "⏹️";
      default:
        return "❓";
    }
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return "0 Bytes";
    const k = 1024;
    const sizes = ["Bytes", "KB", "MB", "GB"];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
  };

  return (
    <div
      className={`upload-list-item upload-list-item--${item.state.status} ${className}`}
      style={{
        padding: "12px",
        border: "1px solid #e0e0e0",
        borderRadius: "6px",
        marginBottom: "8px",
        backgroundColor: "#fff",
        transition: "all 0.2s ease",
        ...style,
      }}
    >
      {/* Header with filename and status */}
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "8px",
        }}
      >
        <div
          style={{ display: "flex", alignItems: "center", gap: "8px", flex: 1 }}
        >
          <span style={{ fontSize: "16px" }}>
            {getStatusIcon(item.state.status)}
          </span>
          <span style={{ fontWeight: "500", flex: 1 }}>
            {item.file instanceof File ? item.file.name : "File"}
          </span>
        </div>
        <span
          style={{
            fontSize: "12px",
            color: getStatusColor(item.state.status),
            fontWeight: "500",
            textTransform: "uppercase",
          }}
        >
          {item.state.status}
        </span>
      </div>

      {/* Progress bar for uploading items */}
      {item.state.status === "uploading" && (
        <div style={{ marginBottom: "8px" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: "4px",
            }}
          >
            <span style={{ fontSize: "12px", color: "#666" }}>
              {item.state.progress}%
            </span>
            {showDetails && item.state.totalBytes && (
              <span style={{ fontSize: "12px", color: "#666" }}>
                {formatFileSize(item.state.bytesUploaded)} /{" "}
                {formatFileSize(item.state.totalBytes)}
              </span>
            )}
          </div>
          <div
            style={{
              width: "100%",
              height: "6px",
              backgroundColor: "#e0e0e0",
              borderRadius: "3px",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                width: `${item.state.progress}%`,
                height: "100%",
                backgroundColor: "#007bff",
                transition: "width 0.2s ease",
              }}
            />
          </div>
        </div>
      )}

      {/* Details section */}
      {showDetails && (
        <div style={{ fontSize: "12px", color: "#666", marginBottom: "8px" }}>
          {item.state.totalBytes && (
            <span>{formatFileSize(item.state.totalBytes)}</span>
          )}
          {item.state.status === "uploading" && item.state.progress > 0 && (
            <span> • Progress: {item.state.progress}%</span>
          )}
          {item.state.status === "error" && item.state.error && (
            <div style={{ color: "#dc3545", marginTop: "4px" }}>
              {item.state.error.message}
            </div>
          )}
        </div>
      )}

      {/* Action buttons */}
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        {item.state.status === "idle" && (
          <>
            <button
              type="button"
              onClick={() => actions.startItem(item)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #007bff",
                backgroundColor: "#007bff",
                color: "white",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Start
            </button>
            <button
              type="button"
              onClick={() => actions.removeItem(item.id)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #6c757d",
                backgroundColor: "transparent",
                color: "#6c757d",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Remove
            </button>
          </>
        )}

        {item.state.status === "uploading" && (
          <button
            type="button"
            onClick={() => actions.abortItem(item)}
            style={{
              padding: "4px 8px",
              fontSize: "12px",
              border: "1px solid #dc3545",
              backgroundColor: "transparent",
              color: "#dc3545",
              borderRadius: "4px",
              cursor: "pointer",
            }}
          >
            Cancel
          </button>
        )}

        {item.state.status === "error" && (
          <>
            <button
              type="button"
              onClick={() => actions.retryItem(item)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #28a745",
                backgroundColor: "#28a745",
                color: "white",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Retry
            </button>
            <button
              type="button"
              onClick={() => actions.removeItem(item.id)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #6c757d",
                backgroundColor: "transparent",
                color: "#6c757d",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Remove
            </button>
          </>
        )}

        {item.state.status === "success" && (
          <button
            type="button"
            onClick={() => actions.removeItem(item.id)}
            style={{
              padding: "4px 8px",
              fontSize: "12px",
              border: "1px solid #6c757d",
              backgroundColor: "transparent",
              color: "#6c757d",
              borderRadius: "4px",
              cursor: "pointer",
            }}
          >
            Remove
          </button>
        )}

        {item.state.status === "aborted" && (
          <>
            <button
              type="button"
              onClick={() => actions.retryItem(item)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #007bff",
                backgroundColor: "#007bff",
                color: "white",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Retry
            </button>
            <button
              type="button"
              onClick={() => actions.removeItem(item.id)}
              style={{
                padding: "4px 8px",
                fontSize: "12px",
                border: "1px solid #6c757d",
                backgroundColor: "transparent",
                color: "#6c757d",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Remove
            </button>
          </>
        )}
      </div>
    </div>
  );
}

// packages/clients/vue/src/components/UploadList.vue
<script setup lang="ts">
/**
 * UploadList - Display a list of uploads with customizable status grouping and sorting
 *
 * Shows the progress and status of multiple file uploads. Supports filtering, sorting,
 * and status-based grouping. Provides flexible slot-based customization for rendering each item.
 *
 * @component
 * @example
 * // Basic upload list
 * <UploadList :uploads="uploads" />
 *
 * @example
 * // Custom item rendering with status indicators
 * <UploadList :uploads="uploads">
 *   <template #item="{ item, isSuccess, isError }">
 *     <div class="upload-item">
 *       <span>{{ item.filename }}</span>
 *       <progress :value="item.progress" max="100"></progress>
 *       <span :class="{ success: isSuccess, error: isError }">
 *         {{ item.state.status }}
 *       </span>
 *     </div>
 *   </template>
 * </UploadList>
 *
 * @example
 * // With filtering and sorting
 * <UploadList
 *   :uploads="uploads"
 *   :filter="item => item.state.status === 'success'"
 *   :sort-by="(a, b) => a.uploadedAt - b.uploadedAt"
 * />
 */
import type { VNodeChild } from "vue";
import { computed } from "vue";
import type { UploadItem } from "../composables";
import { isBrowserFile } from "../utils";

/**
 * Props for the UploadList component
 * @property {UploadItem[]} uploads - Array of upload items to display
 * @property {Function} filter - Optional filter for which items to display
 * @property {Function} sortBy - Optional sorting function for items (a, b) => number
 */
export interface UploadListProps {
  /**
   * Array of upload items to display
   */
  uploads: UploadItem[];

  /**
   * Optional filter for which items to display
   */
  filter?: (item: UploadItem) => boolean;

  /**
   * Optional sorting function for items
   */
  sortBy?: (a: UploadItem, b: UploadItem) => number;
}

const props = defineProps<UploadListProps>();

defineSlots<{
  item(props: {
    item: UploadItem;
    index: number;
    isUploading: boolean;
    isSuccess: boolean;
    isError: boolean;
    formatFileSize: (bytes: number) => string;
  }): VNodeChild;
  default?(props: {
    items: UploadItem[];
    itemsByStatus: {
      idle: UploadItem[];
      uploading: UploadItem[];
      success: UploadItem[];
      error: UploadItem[];
      aborted: UploadItem[];
    };
  }): VNodeChild;
}>();

// Apply filtering and sorting
const filteredItems = computed(() => {
  let items = props.uploads;

  if (props.filter) {
    items = items.filter(props.filter);
  }

  if (props.sortBy) {
    items = [...items].sort(props.sortBy);
  }

  return items;
});

// Group items by status
const itemsByStatus = computed(() => ({
  idle: filteredItems.value.filter((item) => item.state.status === "idle"),
  uploading: filteredItems.value.filter(
    (item) => item.state.status === "uploading",
  ),
  success: filteredItems.value.filter(
    (item) => item.state.status === "success",
  ),
  error: filteredItems.value.filter((item) => item.state.status === "error"),
  aborted: filteredItems.value.filter(
    (item) => item.state.status === "aborted",
  ),
}));

// Helper function to format file sizes
const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return "0 Bytes";
  const k = 1024;
  const sizes = ["Bytes", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / k ** i).toFixed(2))} ${sizes[i]}`;
};

// Helper function to get status icon
const getStatusIcon = (status: string): string => {
  switch (status) {
    case "idle":
      return "⏳";
    case "uploading":
      return "📤";
    case "success":
      return "✅";
    case "error":
      return "❌";
    case "aborted":
      return "⏹️";
    default:
      return "❓";
  }
};

// Helper function to get status color
const getStatusColor = (status: string): string => {
  switch (status) {
    case "idle":
      return "#6c757d";
    case "uploading":
      return "#007bff";
    case "success":
      return "#28a745";
    case "error":
      return "#dc3545";
    case "aborted":
      return "#6c757d";
    default:
      return "#6c757d";
  }
};
</script>

<template>
  <div class="upload-list">
    <slot :items="filteredItems" :items-by-status="itemsByStatus">
      <!-- Default rendering: simple list of upload items -->
      <div
        v-for="(item, index) in filteredItems"
        :key="item.id"
        class="upload-list__item"
        :class="`upload-list__item--${item.state.status}`"
      >
        <slot
          name="item"
          :item="item"
          :index="index"
          :is-uploading="item.state.status === 'uploading'"
          :is-success="item.state.status === 'success'"
          :is-error="item.state.status === 'error'"
          :format-file-size="formatFileSize"
        >
          <!-- Default item template -->
          <div class="upload-list__item-header">
            <span class="upload-list__item-icon">
              {{ getStatusIcon(item.state.status) }}
            </span>
            <span class="upload-list__item-name">
              {{ isBrowserFile(item.file) ? item.file.name : 'File' }}
            </span>
            <span
              class="upload-list__item-status"
              :style="{ color: getStatusColor(item.state.status) }"
            >
              {{ item.state.status.toUpperCase() }}
            </span>
          </div>

          <div v-if="item.state.totalBytes" class="upload-list__item-size">
            {{ formatFileSize(item.state.totalBytes) }}
          </div>

          <div v-if="item.state.status === 'uploading'" class="upload-list__item-progress">
            <div class="upload-list__progress-bar">
              <div
                class="upload-list__progress-fill"
                :style="{ width: `${item.state.progress}%` }"
              />
            </div>
            <span class="upload-list__progress-text">{{ item.state.progress }}%</span>
          </div>

          <div v-if="item.state.status === 'error' && item.state.error" class="upload-list__item-error">
            {{ item.state.error.message }}
          </div>
        </slot>
      </div>
    </slot>
  </div>
</template>

<style scoped>
.upload-list {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.upload-list__item {
  padding: 0.75rem;
  border: 1px solid #e0e0e0;
  border-radius: 0.375rem;
  background-color: #fff;
}

.upload-list__item-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.5rem;
}

.upload-list__item-icon {
  font-size: 1rem;
}

.upload-list__item-name {
  flex: 1;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.upload-list__item-status {
  font-size: 0.75rem;
  font-weight: 600;
  text-transform: uppercase;
}

.upload-list__item-size {
  font-size: 0.75rem;
  color: #666;
  margin-bottom: 0.5rem;
}

.upload-list__item-progress {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.upload-list__progress-bar {
  flex: 1;
  height: 0.375rem;
  background-color: #e0e0e0;
  border-radius: 0.1875rem;
  overflow: hidden;
}

.upload-list__progress-fill {
  height: 100%;
  background-color: #007bff;
  transition: width 0.2s ease;
}

.upload-list__progress-text {
  font-size: 0.75rem;
  color: #666;
  min-width: 3rem;
  text-align: right;
}

.upload-list__item-error {
  margin-top: 0.5rem;
  padding: 0.5rem;
  background-color: #f8d7da;
  color: #721c24;
  font-size: 0.75rem;
  border-radius: 0.25rem;
}
</style>
