// examples/react-client/src/components/DragDropUploadExample.tsx
import { useDragDrop, useMultiUpload } from "@uploadista/react";
import { FilePreview } from "./FilePreview";
import { Card } from "./ui/card";

export function DragDropUploadExample() {
  const multiUpload = useMultiUpload({
    maxConcurrent: 3,
    onComplete: (results) => {
      console.log("All uploads complete:", results);
    },
  });

  const dragDrop = useDragDrop({
    accept: ["image/*", "video/*", ".pdf"],
    maxFiles: 10,
    maxFileSize: 50 * 1024 * 1024, // 50MB
    onFilesReceived: (files) => {
      multiUpload.addFiles(files);
      multiUpload.startAll();
    },
    onValidationError: (errors) => {
      console.error("Validation errors:", errors);
    },
  });

  return (
    <Card className="p-8">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-3">
          Drag & Drop Upload
        </h2>
        <p className="text-gray-600 leading-relaxed">
          Drag and drop files into the upload zone, or click to select files.
          This example supports images, videos, and PDF files up to 50MB each,
          with a maximum of 10 files at once.
        </p>
      </div>

      <div className="space-y-6">
        {/* Drag & Drop Zone */}
        {/** biome-ignore lint/a11y/noStaticElementInteractions: just an example of drag and drop zone */}
        {/** biome-ignore lint/a11y/useKeyWithClickEvents: just an example of drag and drop zone */}
        <div
          {...dragDrop.dragHandlers}
          onClick={dragDrop.openFilePicker}
          className={`
            relative border-3 border-dashed rounded-2xl p-12 text-center cursor-pointer transition-all duration-300
            ${
              dragDrop.state.isDragging
                ? "border-indigo-500 bg-gradient-to-br from-indigo-50 to-purple-50 scale-102"
                : "border-gray-300 bg-gradient-to-br from-gray-50 to-white hover:border-indigo-400 hover:bg-gradient-to-br hover:from-indigo-50 hover:to-purple-50"
            }
          `}
        >
          <input {...dragDrop.inputProps} />

          <div className="pointer-events-none">
            {dragDrop.state.isDragging ? (
              <>
                <div className="text-7xl mb-4 animate-bounce">📁</div>
                <div className="text-2xl font-bold text-indigo-600 mb-2">
                  Drop your files here...
                </div>
              </>
            ) : (
              <>
                <div className="mb-6">
                  <div className="inline-flex items-center justify-center w-20 h-20 rounded-full bg-gradient-to-br from-indigo-500 to-purple-500 text-white mb-4">
                    <svg
                      className="w-10 h-10"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      aria-hidden="true"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
                      />
                    </svg>
                  </div>
                </div>
                <div className="text-2xl font-bold text-gray-900 mb-2">
                  Drag & drop files here
                </div>
                <div className="text-gray-500 mb-4">or click to browse</div>
                <div className="inline-flex items-center gap-2 text-sm text-gray-400">
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <span>Images, videos, PDFs • Max 50MB • Up to 10 files</span>
                </div>
              </>
            )}
          </div>
        </div>

        {/* Validation Errors */}
        {dragDrop.state.errors.length > 0 && (
          <div className="bg-gradient-to-br from-red-50 to-rose-50 rounded-2xl p-6 border border-red-200">
            <div className="flex items-start gap-3 mb-3">
              <div className="flex-shrink-0 w-10 h-10 bg-red-500 rounded-full flex items-center justify-center">
                <svg
                  className="w-6 h-6 text-white"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                  />
                </svg>
              </div>
              <div className="flex-1">
                <h3 className="text-lg font-bold text-red-900 mb-2">
                  Validation Errors
                </h3>
                <ul className="space-y-1">
                  {dragDrop.state.errors.map((error) => (
                    <li key={error} className="text-red-700 text-sm">
                      • {error}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* Upload Progress Section */}
        {multiUpload.items.length > 0 && (
          <>
            <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl p-6 border border-indigo-100">
              <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Overall Progress
                  </div>
                  <div className="text-2xl font-bold text-gray-900">
                    {multiUpload.state.progress}%
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Files Uploading
                  </div>
                  <div className="text-2xl font-bold text-blue-600">
                    {multiUpload.state.uploading}
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Completed
                  </div>
                  <div className="text-2xl font-bold text-green-600">
                    {multiUpload.state.successful}
                  </div>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="relative h-3 bg-gray-200 rounded-full overflow-hidden mb-4">
                <div
                  className="absolute inset-y-0 left-0 progress-bar-gradient transition-all duration-300 ease-out"
                  style={{
                    width: `${multiUpload.state.progress}%`,
                  }}
                />
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-3 gap-3">
                <button
                  type="button"
                  onClick={multiUpload.abortAll}
                  disabled={multiUpload.state.uploading === 0}
                  className="px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
                >
                  Abort All
                </button>
                <button
                  type="button"
                  onClick={multiUpload.retryFailed}
                  disabled={multiUpload.state.failed === 0}
                  className="px-6 py-3 bg-orange-600 text-white font-semibold rounded-xl hover:bg-orange-700 focus:outline-none focus:ring-4 focus:ring-orange-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
                >
                  Retry Failed
                </button>
                <button
                  type="button"
                  onClick={multiUpload.clearAll}
                  className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md"
                >
                  Clear All
                </button>
              </div>
            </div>

            {/* File List */}
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                Uploaded Files
              </h3>
              <div className="space-y-3">
                {multiUpload.items.map((item) => (
                  <div
                    key={item.id}
                    className="bg-white rounded-xl border border-gray-200 p-4 hover:shadow-md transition-all"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3 flex-1 min-w-0">
                        <div className="flex-shrink-0">
                          <svg
                            className="w-8 h-8 text-gray-400"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={2}
                              d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
                            />
                          </svg>
                        </div>
                        <span className="font-semibold text-gray-900 truncate">
                          {item.file instanceof File ? item.file.name : "File"}
                        </span>
                      </div>
                      <span
                        className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold flex-shrink-0 ml-3 ${
                          item.state.status === "uploading"
                            ? "bg-blue-100 text-blue-700"
                            : item.state.status === "success"
                              ? "bg-green-100 text-green-700"
                              : item.state.status === "error"
                                ? "bg-red-100 text-red-700"
                                : "bg-gray-100 text-gray-700"
                        }`}
                      >
                        {item.state.status}
                      </span>
                    </div>

                    {/* Progress Bar */}
                    {item.state.status !== "idle" && (
                      <div className="relative h-2 bg-gray-200 rounded-full overflow-hidden mb-3">
                        <div
                          className={`absolute inset-y-0 left-0 transition-all duration-300 ease-out rounded-full ${
                            item.state.status === "success"
                              ? "bg-green-500"
                              : item.state.status === "error"
                                ? "bg-red-500"
                                : "progress-bar-gradient"
                          }`}
                          style={{ width: `${item.state.progress}%` }}
                        />
                      </div>
                    )}

                    {/* File Preview for successful uploads */}
                    {item.state.status === "success" && (
                      <div className="mt-3">
                        <FilePreview result={item.state.result} />
                      </div>
                    )}

                    {/* Error Message */}
                    {item.state.status === "error" && item.state.error && (
                      <div className="mt-3 flex items-start gap-2 text-sm text-red-700 bg-red-50 rounded-lg p-2">
                        <svg
                          className="w-4 h-4 flex-shrink-0 mt-0.5"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                          />
                        </svg>
                        <span>Error: {item.state.error.message}</span>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </>
        )}
      </div>
    </Card>
  );
}

// examples/vue-client/src/components/DragDropUploadExample.vue
<script setup lang="ts">
import { useDragDrop, useMultiUpload } from "@uploadista/vue";
import { computed, ref } from "vue";
import FilePreview from "./FilePreview.vue";
import Card from "./ui/Card.vue";

const errors = ref<string[]>([]);
const inputRef = ref<HTMLInputElement | null>(null);

const multiUpload = useMultiUpload({
  maxConcurrent: 3,
  onUploadSuccess: (item) => {
    console.log("Drag/drop upload complete:", item.file);
  },
  onUploadError: (item, error) => {
    console.error("Drag/drop upload failed:", item.file, error);
  },
});

const dragDrop = useDragDrop({
  accept: ["image/*", "video/*", ".pdf"],
  maxFiles: 8,
  multiple: true,
  onFilesReceived: (files) => {
    errors.value = [];
    multiUpload.addFiles(files);
    if (!multiUpload.state.value.isUploading) {
      multiUpload.startAll();
    }
  },
  onValidationError: (validationErrors) => {
    errors.value = validationErrors;
  },
});

const hasPending = computed(
  () =>
    multiUpload.items.value.filter((item) => item.state.status === "idle")
      .length > 0,
);

const isBrowserFile = (value: unknown): value is File =>
  typeof File !== "undefined" && value instanceof File;

const handleInputClick = () => {
  inputRef.value?.click();
};
</script>

<template>
  <Card class="p-8 space-y-8">
    <header class="space-y-2">
      <h2 class="text-3xl font-bold text-gray-900">Drag &amp; Drop Uploads</h2>
      <p class="text-gray-600 leading-relaxed">
        Drop files or choose them manually. Uploads start automatically and the
        queue runs with concurrency limits.
      </p>
    </header>

    <section>
      <div
        class="relative rounded-3xl border-2 border-dashed p-12 text-center transition-all duration-300 ease-out"
        :class="[
          dragDrop.state.value.isOver
            ? 'border-primary bg-gradient-to-br from-indigo-50 via-white to-purple-50'
            : 'border-gray-300 bg-white',
        ]"
        @dragenter="dragDrop.onDragEnter"
        @dragover="dragDrop.onDragOver"
        @dragleave="dragDrop.onDragLeave"
        @drop="dragDrop.onDrop"
        @click="handleInputClick"
      >
        <div class="pointer-events-none space-y-3">
          <div
            class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-r from-indigo-500 to-purple-600 text-white shadow-lg"
          >
            <svg
              class="h-8 w-8"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"
              />
            </svg>
          </div>
          <h3 class="text-xl font-semibold text-gray-900">
            Drop files to upload
          </h3>
          <p class="text-sm text-gray-600">
            Accepts images, videos, and PDFs. Up to eight files per batch.
          </p>
          <p class="text-xs text-gray-500">
            Click anywhere in this card to open the file picker.
          </p>
        </div>
        <input
          ref="inputRef"
          class="hidden"
          v-bind="dragDrop.inputProps"
          @change="dragDrop.onInputChange"
        />
      </div>
      <ul v-if="errors.length" class="mt-4 space-y-2">
        <li
          v-for="error in errors"
          :key="error"
          class="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"
        >
          {{ error }}
        </li>
      </ul>
    </section>

    <section v-if="multiUpload.items.value.length > 0" class="space-y-4">
      <div class="flex flex-wrap gap-3">
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md hover:from-indigo-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="multiUpload.state.value.isUploading || !hasPending"
          @click="multiUpload.startAll"
        >
          Start Pending
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold bg-red-600 text-white shadow-md hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="!multiUpload.state.value.isUploading"
          @click="multiUpload.abortAll"
        >
          Abort Active
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="multiUpload.state.value.total === 0"
          @click="multiUpload.clearAll"
        >
          Clear Queue
        </button>
      </div>

      <div class="space-y-3">
        <article
          v-for="item in multiUpload.items.value"
          :key="item.id"
          class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"
        >
          <div class="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
            <div>
              <p class="text-base font-semibold text-gray-900">
                {{ isBrowserFile(item.file) ? item.file.name : "Binary Data" }}
              </p>
              <p class="text-xs text-gray-500">
                Status:
                <span class="capitalize">{{ item.state.status }}</span>
              </p>
            </div>
            <div class="flex gap-2">
              <button
                v-if="item.state.status === 'uploading'"
                type="button"
                class="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700 hover:bg-red-100 transition-all"
                @click="multiUpload.abortUpload(item.id)"
              >
                Abort
              </button>
              <button
                v-if="['error', 'aborted'].includes(item.state.status)"
                type="button"
                class="rounded-lg border border-orange-200 bg-orange-50 px-3 py-2 text-sm font-medium text-orange-700 hover:bg-orange-100 transition-all"
                @click="multiUpload.retryUpload(item.id)"
              >
                Retry
              </button>
              <button
                type="button"
                class="rounded-lg border border-gray-200 px-3 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50 transition-all"
                @click="multiUpload.removeItem(item.id)"
              >
                Remove
              </button>
            </div>
          </div>
          <div class="mt-3 space-y-2">
            <div class="flex items-center justify-between text-sm text-gray-600">
              <span>Progress</span>
              <span>{{ item.state.progress }}%</span>
            </div>
            <div class="relative h-2 rounded-full bg-gray-200 overflow-hidden">
              <div
                class="absolute inset-y-0 left-0 bg-gradient-to-r from-indigo-500 to-purple-600 transition-all"
                :style="{ width: `${item.state.progress}%` }"
              />
            </div>
          </div>
          <FilePreview
            v-if="item.state.result && isBrowserFile(item.file)"
            :file="item.file"
            :result="item.state.result ?? undefined"
          />
        </article>
      </div>
    </section>

    <section v-else class="rounded-2xl border border-dashed border-gray-300 bg-white p-10 text-center">
      <p class="text-gray-500 text-sm">
        The queue is empty. Drag files above or click to select them.
      </p>
    </section>
  </Card>
</template>
