// examples/react-client/src/components/MultiUploadExample.tsx
import { useMultiUpload } from "@uploadista/react";
import { FilePreview } from "./FilePreview";
import { Card } from "./ui/card";

export function MultiUploadExample() {
  const multiUpload = useMultiUpload({
    maxConcurrent: 3,
    onUploadStart: (item) => {
      console.log("Upload started:", item);
    },
    onUploadProgress: (item, progress, bytesUploaded, totalBytes) => {
      console.log(
        "Upload progress:",
        item,
        progress,
        bytesUploaded,
        totalBytes,
      );
    },
    onUploadSuccess: (item, result) => {
      console.log("Upload success:", item, result);
    },
    onUploadError: (item, error) => {
      console.log("Upload error:", item, error);
    },
    onComplete: (results) => {
      console.log("All uploads complete:", results);
      alert(
        `${results.successful.length}/${results.total} files uploaded successfully`,
      );
    },
  });

  const handleFilesSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      multiUpload.addFiles(Array.from(e.target.files));
      multiUpload.startAll();
    }
  };

  return (
    <Card className="p-8">
      <div className="mb-8">
        <h2 className="text-3xl font-bold text-gray-900 mb-3">
          Multiple File Upload
        </h2>
        <p className="text-gray-600 leading-relaxed">
          Upload multiple files concurrently. This example demonstrates batch
          uploading with configurable concurrency limits and individual file
          progress tracking.
        </p>
      </div>

      <div className="space-y-6">
        {/* File Input */}
        <div>
          <label
            htmlFor="multi-file-input"
            className="block text-sm font-semibold text-gray-700 mb-2 uppercase tracking-wide"
          >
            Choose Multiple Files
          </label>
          <input
            id="multi-file-input"
            type="file"
            multiple
            onChange={handleFilesSelect}
            disabled={multiUpload.state.uploading > 0}
            className="block w-full text-gray-700 file:mr-4 file:py-3 file:px-6 file:rounded-xl file:border-0 file:bg-gradient-to-r file:from-indigo-600 file:to-purple-600 file:text-white file:font-semibold file:cursor-pointer hover:file:from-indigo-700 hover:file:to-purple-700 file:transition-all file:shadow-md disabled:opacity-50 disabled:cursor-not-allowed border-2 border-gray-200 rounded-xl focus:outline-none focus:border-indigo-500"
          />
        </div>

        {multiUpload.items.length > 0 && (
          <>
            {/* Overview Section */}
            <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-2xl p-6 border border-indigo-100">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Overall Progress
                  </div>
                  <div className="text-2xl font-bold text-gray-900">
                    {multiUpload.state.progress}%
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Active Uploads
                  </div>
                  <div className="text-2xl font-bold text-blue-600">
                    {multiUpload.state.uploading}
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Successful
                  </div>
                  <div className="text-2xl font-bold text-green-600">
                    {multiUpload.state.successful}
                  </div>
                </div>
                <div className="bg-white rounded-xl p-4 shadow-sm">
                  <div className="text-sm font-semibold text-gray-500 mb-2">
                    Failed
                  </div>
                  <div className="text-2xl font-bold text-red-600">
                    {multiUpload.state.failed}
                  </div>
                </div>
              </div>

              {/* Progress Bar */}
              <div className="relative h-3 bg-gray-200 rounded-full overflow-hidden mb-4">
                <div
                  className="absolute inset-y-0 left-0 progress-bar-gradient transition-all duration-300 ease-out"
                  style={{ width: `${multiUpload.state.progress}%` }}
                />
              </div>

              {/* Action Buttons */}
              <div className="grid grid-cols-3 gap-3">
                <button
                  type="button"
                  onClick={multiUpload.abortAll}
                  disabled={multiUpload.state.uploading === 0}
                  className="px-6 py-3 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 focus:outline-none focus:ring-4 focus:ring-red-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
                >
                  Abort All
                </button>
                <button
                  type="button"
                  onClick={multiUpload.retryFailed}
                  disabled={multiUpload.state.failed === 0}
                  className="px-6 py-3 bg-orange-600 text-white font-semibold rounded-xl hover:bg-orange-700 focus:outline-none focus:ring-4 focus:ring-orange-100 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-md"
                >
                  Retry Failed
                </button>
                <button
                  type="button"
                  onClick={multiUpload.clearAll}
                  className="px-6 py-3 bg-gradient-to-r from-indigo-600 to-purple-600 text-white font-semibold rounded-xl hover:from-indigo-700 hover:to-purple-700 focus:outline-none focus:ring-4 focus:ring-indigo-100 transition-all shadow-md"
                >
                  Clear All
                </button>
              </div>
            </div>

            {/* File List */}
            <div>
              <h3 className="text-xl font-bold text-gray-900 mb-4">
                File List
              </h3>
              <div className="space-y-3">
                {multiUpload.items.map((item) => (
                  <div
                    key={item.id}
                    className="bg-white rounded-xl border border-gray-200 p-4 hover:shadow-md transition-all"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className="flex items-center gap-3 flex-1 min-w-0">
                        <div className="flex-shrink-0">
                          <svg
                            className="w-8 h-8 text-gray-400"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke="currentColor"
                            aria-hidden="true"
                          >
                            <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={2}
                              d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z"
                            />
                          </svg>
                        </div>
                        <span className="font-semibold text-gray-900 truncate">
                          {item.file instanceof File ? item.file.name : "File"}
                        </span>
                      </div>
                      <span
                        className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold flex-shrink-0 ml-3 ${
                          item.state.status === "uploading"
                            ? "bg-blue-100 text-blue-700"
                            : item.state.status === "success"
                              ? "bg-green-100 text-green-700"
                              : item.state.status === "error"
                                ? "bg-red-100 text-red-700"
                                : "bg-gray-100 text-gray-700"
                        }`}
                      >
                        {item.state.status}
                      </span>
                    </div>

                    {/* Progress Bar */}
                    <div className="relative h-2 bg-gray-200 rounded-full overflow-hidden mb-3">
                      <div
                        className={`absolute inset-y-0 left-0 transition-all duration-300 ease-out rounded-full ${
                          item.state.status === "success"
                            ? "bg-green-500"
                            : item.state.status === "error"
                              ? "bg-red-500"
                              : "progress-bar-gradient"
                        }`}
                        style={{ width: `${item.state.progress}%` }}
                      />
                    </div>

                    {/* Action Buttons */}
                    <div className="flex gap-2">
                      {item.state.status === "uploading" && (
                        <button
                          type="button"
                          onClick={() => multiUpload.abortUpload(item.id)}
                          className="flex-1 px-4 py-2 bg-red-600 text-white text-sm font-semibold rounded-lg hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-100 transition-all"
                        >
                          Abort
                        </button>
                      )}
                      {item.state.status === "error" && (
                        <button
                          type="button"
                          onClick={() => multiUpload.retryUpload(item.id)}
                          className="flex-1 px-4 py-2 bg-orange-600 text-white text-sm font-semibold rounded-lg hover:bg-orange-700 focus:outline-none focus:ring-2 focus:ring-orange-100 transition-all"
                        >
                          Retry
                        </button>
                      )}
                      {(item.state.status === "idle" ||
                        item.state.status === "error") && (
                        <button
                          type="button"
                          onClick={() => multiUpload.removeFile(item.id)}
                          className="flex-1 px-4 py-2 bg-gray-600 text-white text-sm font-semibold rounded-lg hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-100 transition-all"
                        >
                          Remove
                        </button>
                      )}
                    </div>

                    {/* File Preview for successful uploads */}
                    {item.state.status === "success" && (
                      <div className="mt-3">
                        <FilePreview
                          file={
                            item.file instanceof File ? item.file : undefined
                          }
                          result={item.state.result}
                        />
                      </div>
                    )}

                    {/* Error Message */}
                    {item.state.error && (
                      <div className="mt-3 flex items-start gap-2 text-sm text-red-700 bg-red-50 rounded-lg p-2">
                        <svg
                          className="w-4 h-4 flex-shrink-0 mt-0.5"
                          fill="none"
                          viewBox="0 0 24 24"
                          stroke="currentColor"
                          aria-hidden="true"
                        >
                          <path
                            strokeLinecap="round"
                            strokeLinejoin="round"
                            strokeWidth={2}
                            d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                          />
                        </svg>
                        <span>Error: {item.state.error.message}</span>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          </>
        )}
      </div>
    </Card>
  );
}

// examples/vue-client/src/components/MultiUploadExample.vue
<script setup lang="ts">
import { useMultiUpload } from "@uploadista/vue";
import { computed } from "vue";
import FilePreview from "./FilePreview.vue";
import Card from "./ui/Card.vue";

const isBrowserFile = (value: unknown): value is File =>
  typeof File !== "undefined" && value instanceof File;

const multiUpload = useMultiUpload({
  maxConcurrent: 3,
  onUploadStart: (item) => {
    console.log("Upload started:", item.file);
  },
  onUploadSuccess: (item, result) => {
    console.log("Upload complete:", item.file, result);
  },
  onUploadError: (item, error) => {
    console.error("Upload failed:", item.file, error);
  },
  onComplete: (results) => {
    console.log(
      `Batch complete: ${results.successful.length}/${results.total} succeeded`,
    );
  },
});

const failedItems = computed(
  () =>
    multiUpload.items.value.filter((item) =>
      ["error", "aborted"].includes(item.state.status),
    ) ?? [],
);

const handleFileChange = (event: Event) => {
  const files = Array.from((event.target as HTMLInputElement).files || []);
  if (files.length) {
    multiUpload.addFiles(files);
    // Auto-start uploads if nothing active
    if (!multiUpload.state.value.isUploading) {
      multiUpload.startAll();
    }
  }
};
</script>

<template>
  <Card class="p-8 space-y-8">
    <header class="space-y-2">
      <h2 class="text-3xl font-bold text-gray-900">Multiple Uploads</h2>
      <p class="text-gray-600 leading-relaxed">
        Queue multiple files, monitor aggregate progress, and manage retry
        states. Useful for testing chunking, concurrency, and resumable uploads.
      </p>
    </header>

    <section class="space-y-4">
      <label
        class="block text-sm font-semibold text-gray-700 mb-2 uppercase tracking-wide"
        for="multi-upload-input"
      >
        Select Files
      </label>
      <input
        id="multi-upload-input"
        type="file"
        multiple
        class="block w-full text-gray-700 file:mr-4 file:py-3 file:px-6 file:rounded-xl file:border-0 file:bg-gradient-to-r file:from-indigo-600 file:to-purple-600 file:text-white file:font-semibold file:cursor-pointer hover:file:from-indigo-700 hover:file:to-purple-700 file:transition-all file:shadow-md border-2 border-gray-200 rounded-xl focus:outline-none focus:border-indigo-500"
        @change="handleFileChange"
      />
    </section>
    <section v-if="multiUpload.items.value.length > 0">


      <div class="grid gap-4 rounded-2xl border border-gray-200 bg-white p-6 md:grid-cols-3 mb-4">
        <div>
          <p class="text-sm font-semibold text-gray-500 mb-1">Total Files</p>
          <p class="text-3xl font-bold text-gray-900">
            {{ multiUpload.state.value.total }}
          </p>
          <p class="text-xs text-gray-500">
            {{ multiUpload.state.value.completed }} completed,
            {{ multiUpload.state.value.uploading }} in progress
          </p>
        </div>
        <div>
          <p class="text-sm font-semibold text-gray-500 mb-1">Progress</p>
          <p class="text-3xl font-bold text-gray-900">
            {{ multiUpload.state.value.progress }}%
          </p>
          <p class="text-xs text-gray-500">
            {{ multiUpload.state.value.totalBytesUploaded?.toLocaleString() ?? 0 }} /
            {{ multiUpload.state.value.totalBytes?.toLocaleString() ?? 0 }} bytes
          </p>
        </div>
        <div>
          <p class="text-sm font-semibold text-gray-500 mb-1">Status</p>
          <p class="text-3xl font-bold text-gray-900">
            {{
              multiUpload.state.value.failed > 0
                ? `${multiUpload.state.value.failed} failed`
                : "Healthy"
            }}
          </p>
          <p class="text-xs text-gray-500">
            {{ multiUpload.state.value.successful }} succeeded
          </p>
        </div>
      </div>

      <div class="flex flex-wrap gap-3">
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md hover:from-indigo-700 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="multiUpload.state.value.isUploading || !multiUpload.state.value.total"
          @click="multiUpload.startAll"
        >
          Start Uploads
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold bg-red-600 text-white shadow-md hover:bg-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="!multiUpload.state.value.isUploading"
          @click="multiUpload.abortAll"
        >
          Abort All
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold bg-orange-500 text-white shadow-md hover:bg-orange-600 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="failedItems.length === 0"
          @click="multiUpload.retryFailed"
        >
          Retry Failed
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="multiUpload.state.value.completed === 0"
          @click="multiUpload.clearCompleted"
        >
          Clear Completed
        </button>
        <button
          type="button"
          class="px-5 py-3 rounded-xl font-semibold border border-gray-200 bg-white text-gray-700 shadow-sm hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
          :disabled="multiUpload.state.value.total === 0"
          @click="multiUpload.clearAll"
        >
          Reset List
        </button>
      </div>
    </section>

    <section v-if="multiUpload.items.value.length > 0" class="space-y-4">
      <h3 class="text-lg font-semibold text-gray-900">Upload Queue</h3>
      <div class="space-y-4">
        <article
          v-for="item in multiUpload.items.value"
          :key="item.id"
          class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm"
        >
          <div class="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
            <div>
              <p class="text-base font-semibold text-gray-900">
                {{ isBrowserFile(item.file) ? item.file.name : "Binary Data" }}
              </p>
              <p class="text-xs text-gray-500">
                Status:
                <span class="capitalize">{{ item.state.status }}</span>
              </p>
            </div>
            <div class="flex gap-2">
              <button
                type="button"
                class="rounded-lg border border-gray-200 px-3 py-2 text-sm font-medium text-gray-600 hover:bg-gray-50 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                :disabled="item.state.status === 'uploading'"
                @click="multiUpload.removeItem(item.id)"
              >
                Remove
              </button>
              <button
                v-if="['error', 'aborted'].includes(item.state.status)"
                type="button"
                class="rounded-lg border border-orange-200 bg-orange-50 px-3 py-2 text-sm font-medium text-orange-700 hover:bg-orange-100 transition-all"
                @click="multiUpload.retryUpload(item.id)"
              >
                Retry
              </button>
              <button
                v-if="item.state.status === 'uploading'"
                type="button"
                class="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700 hover:bg-red-100 transition-all"
                @click="multiUpload.abortUpload(item.id)"
              >
                Abort
              </button>
            </div>
          </div>

          <div class="mt-4 space-y-2">
            <div class="flex items-center justify-between text-sm text-gray-600">
              <span>Progress</span>
              <span>{{ item.state.progress }}%</span>
            </div>
            <div class="relative h-2 rounded-full bg-gray-200 overflow-hidden">
              <div
                class="absolute inset-y-0 left-0 bg-gradient-to-r from-indigo-500 to-purple-600 transition-all"
                :style="{ width: `${item.state.progress}%` }"
              />
            </div>
          </div>
          <FilePreview
            v-if="item.state.result && isBrowserFile(item.file)"
            :file="item.file"
            :result="item.state.result ?? undefined"
          />
        </article>
      </div>
    
    </section>

    <section v-else class="rounded-2xl border border-dashed border-gray-300 bg-white p-10 text-center">
      <p class="text-gray-500">
        Select files to start testing concurrent uploads. Drag &amp; drop also
        works in the drag-and-drop tab.
      </p>
    </section>
  </Card>
</template>
