// packages/clients/vue/src/components/UploadZone.vue
<script setup lang="ts">
/**
 * UploadZone - A flexible file upload component with drag-and-drop support
 *
 * Provides a drag-and-drop zone and file picker for uploading files. Supports both single
 * and multiple file uploads with validation. Emits events for file selection and upload events.
 *
 * @component
 * @example
 * // Basic single file upload
 * <UploadZone @file-select="handleFiles" />
 *
 * @example
 * // Multiple files with validation
 * <UploadZone
 *   multiple
 *   accept={["image/*"]}
 *   :max-file-size="10 * 1024 * 1024"
 *   @file-select="handleFiles"
 *   @validation-error="handleErrors"
 * >
 *   <template #default="{ isDragging, errors, openFilePicker }">
 *     <div :class="{ dragging: isDragging }" @click="openFilePicker">
 *       <p>{{ isDragging ? 'Drop files here' : 'Click or drag files here' }}</p>
 *       <div v-if="errors.length">
 *         <p v-for="error in errors" :key="error">{{ error }}</p>
 *       </div>
 *     </div>
 *   </template>
 * </UploadZone>
 *
 * @emits file-select - When files are selected/dropped
 * @emits upload-start - When upload begins
 * @emits validation-error - When validation fails
 */
import type { UploadOptions } from "@uploadista/client-browser";
import { computed, ref } from "vue";
import type { MultiUploadOptions } from "../composables";
import { useDragDrop, useMultiUpload, useUpload } from "../composables";

/**
 * Props for the UploadZone component
 * @property {string[]} accept - Accepted file types (MIME types or file extensions)
 * @property {boolean} multiple - Whether to allow multiple files (default: true)
 * @property {boolean} disabled - Whether the upload zone is disabled (default: false)
 * @property {number} maxFileSize - Maximum file size in bytes
 * @property {Function} validator - Custom validation function for files
 * @property {MultiUploadOptions} multiUploadOptions - Multi-upload options (only used when multiple=true)
 * @property {UploadOptions} uploadOptions - Single upload options (only used when multiple=false)
 */
export interface UploadZoneProps {
  /**
   * Accepted file types (MIME types or file extensions)
   */
  accept?: string[];

  /**
   * Whether to allow multiple files
   */
  multiple?: boolean;

  /**
   * Whether the upload zone is disabled
   */
  disabled?: boolean;

  /**
   * Maximum file size in bytes
   */
  maxFileSize?: number;

  /**
   * Custom validation function for files
   */
  validator?: (files: File[]) => string[] | null;

  /**
   * Multi-upload options (only used when multiple=true)
   */
  multiUploadOptions?: MultiUploadOptions;

  /**
   * Single upload options (only used when multiple=false)
   */
  uploadOptions?: UploadOptions;
}

const props = withDefaults(defineProps<UploadZoneProps>(), {
  multiple: true,
  disabled: false,
});

const emit = defineEmits<{
  "file-select": [files: File[]];
  "upload-start": [files: File[]];
  "validation-error": [errors: string[]];
}>();

defineSlots<{
  // biome-ignore lint/suspicious/noExplicitAny: Vue slot definition requires any
  default(props: {
    isDragging: boolean;
    isOver: boolean;
    isUploading: boolean;
    errors: string[];
    openFilePicker: () => void;
  }): any;
}>();

// Initialize upload composables
const singleUpload = props.multiple
  ? null
  : useUpload(props.uploadOptions || {});
const multiUpload = props.multiple
  ? useMultiUpload(props.multiUploadOptions || {})
  : null;

// Handle files received from drag-drop or file picker
const handleFilesReceived = (files: File[]) => {
  emit("file-select", files);
  emit("upload-start", files);

  if (props.multiple && multiUpload) {
    multiUpload.addFiles(files);
    setTimeout(() => multiUpload.startAll(), 0);
  } else if (!props.multiple && singleUpload && files[0]) {
    singleUpload.upload(files[0]);
  }
};

// Handle validation errors
const handleValidationError = (errors: string[]) => {
  emit("validation-error", errors);
};

// Initialize drag-drop
const dragDrop = useDragDrop({
  accept: props.accept,
  multiple: props.multiple,
  maxFileSize: props.maxFileSize,
  validator: props.validator,
  onFilesReceived: handleFilesReceived,
  onValidationError: handleValidationError,
});

// File input ref
const fileInputRef = ref<HTMLInputElement>();

// Open file picker
// biome-ignore lint/correctness/noUnusedVariables: Used in slot templates
const openFilePicker = () => {
  if (!props.disabled) {
    fileInputRef.value?.click();
  }
};

// Computed states
// biome-ignore lint/correctness/noUnusedVariables: Used in slot templates
const isActive = computed(
  () => dragDrop.state.value.isDragging || dragDrop.state.value.isOver,
);

// biome-ignore lint/correctness/noUnusedVariables: Used in slot templates
const isUploading = computed(() => {
  if (props.multiple && multiUpload) {
    return multiUpload.state.value.isUploading;
  } else if (!props.multiple && singleUpload) {
    return singleUpload.state.value.status === "uploading";
  }
  return false;
});
</script>

<template>
  <div
    class="upload-zone"
    :class="{ 'upload-zone--active': isActive, 'upload-zone--disabled': disabled }"
    @dragenter="!disabled && dragDrop.onDragEnter"
    @dragover="!disabled && dragDrop.onDragOver"
    @dragleave="!disabled && dragDrop.onDragLeave"
    @drop="!disabled && dragDrop.onDrop"
    @click="openFilePicker"
    role="button"
    :tabindex="disabled ? -1 : 0"
    :aria-disabled="disabled"
    :aria-label="multiple ? 'Upload multiple files' : 'Upload a file'"
    @keydown.enter="openFilePicker"
    @keydown.space.prevent="openFilePicker"
  >
    <slot
      :is-dragging="dragDrop.state.value.isDragging"
      :is-over="dragDrop.state.value.isOver"
      :is-uploading="isUploading"
      :errors="[...dragDrop.state.value.errors]"
      :open-file-picker="openFilePicker"
    >
      <!-- Default slot content -->
      <div class="upload-zone__content">
        <p v-if="dragDrop.state.value.isDragging">
          {{ multiple ? 'Drop files here...' : 'Drop file here...' }}
        </p>
        <p v-else>
          {{ multiple ? 'Drag files here or click to select' : 'Drag a file here or click to select' }}
        </p>

        <div v-if="dragDrop.state.value.errors.length > 0" class="upload-zone__errors">
          <p v-for="(error, index) in dragDrop.state.value.errors" :key="index">
            {{ error }}
          </p>
        </div>
      </div>
    </slot>

    <input
      ref="fileInputRef"
      type="file"
      :multiple="dragDrop.inputProps.value.multiple"
      :accept="dragDrop.inputProps.value.accept"
      :disabled="disabled"
      @change="dragDrop.onInputChange"
      style="display: none"
      aria-hidden="true"
    />
  </div>
</template>

<style scoped>
.upload-zone {
  cursor: pointer;
  user-select: none;
}

.upload-zone--disabled {
  cursor: not-allowed;
  opacity: 0.6;
}

.upload-zone__content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.upload-zone__errors {
  margin-top: 0.5rem;
  color: #dc3545;
  font-size: 0.875rem;
}

.upload-zone__errors p {
  margin: 0.25rem 0;
}
</style>

// packages/clients/react/src/components/upload-zone.tsx
/**
 * Upload Zone Components
 *
 * Enhanced error handling features:
 * - MIME type validation with detailed error messages
 * - File count validation (single vs multiple mode)
 * - Custom validation error callbacks
 * - Built-in error display in SimpleUploadZone
 * - Configurable error styling
 */

import type React from "react";
import { useCallback } from "react";
import type {
  DragDropOptions,
  UseDragDropReturn,
} from "../hooks/use-drag-drop";
import { useDragDrop } from "../hooks/use-drag-drop";
import type {
  MultiUploadOptions,
  UseMultiUploadReturn,
} from "../hooks/use-multi-upload";
import { useMultiUpload } from "../hooks/use-multi-upload";
import type { UseUploadOptions, UseUploadReturn } from "../hooks/use-upload";
import { useUpload } from "../hooks/use-upload";

export interface UploadZoneRenderProps {
  /**
   * Drag and drop state and handlers
   */
  dragDrop: UseDragDropReturn;

  /**
   * Single upload functionality (if not using multi-upload)
   */
  upload: UseUploadReturn | null;

  /**
   * Multi-upload functionality (if using multi-upload)
   */
  multiUpload: UseMultiUploadReturn | null;

  /**
   * Helper function to open file picker
   */
  openFilePicker: () => void;

  /**
   * Whether the zone is currently active (dragging or uploading)
   */
  isActive: boolean;

  /**
   * Whether files are being processed
   */
  isProcessing: boolean;
}

export interface UploadZoneProps
  extends Omit<DragDropOptions, "onFilesReceived"> {
  /**
   * Whether to enable multi-file upload mode
   */
  multiple?: boolean;

  /**
   * Multi-upload specific options (only used when multiple=true)
   */
  multiUploadOptions?: MultiUploadOptions;

  /**
   * Single upload specific options (only used when multiple=false)
   */
  uploadOptions?: UseUploadOptions;

  /**
   * Render prop that receives upload zone state and handlers
   */
  children: (props: UploadZoneRenderProps) => React.ReactNode;

  /**
   * Called when files are processed and uploads begin
   */
  onUploadStart?: (files: File[]) => void;

  /**
   * Called when validation errors occur
   */
  onValidationError?: (errors: string[]) => void;
}

/**
 * Headless upload zone component that combines drag and drop functionality
 * with upload management. Uses render props pattern for maximum flexibility.
 * Includes enhanced error handling for MIME type validation and file count validation.
 *
 * @param props - Upload zone configuration and render prop
 * @returns Rendered upload zone using the provided render prop
 *
 * @example
 * ```tsx
 * // Single file upload zone with error handling
 * <UploadZone
 *   multiple={false}
 *   accept={['image/*']}
 *   maxFileSize={5 * 1024 * 1024}
 *   onValidationError={(errors) => {
 *     console.error('Validation errors:', errors);
 *   }}
 *   uploadOptions={{
 *     onSuccess: (result) => console.log('Upload complete:', result),
 *     onError: (error) => console.error('Upload failed:', error),
 *   }}
 * >
 *   {({ dragDrop, upload, openFilePicker, isActive }) => (
 *     <div {...dragDrop.dragHandlers} onClick={openFilePicker}>
 *       {dragDrop.state.isDragging ? (
 *         <p>Drop file here...</p>
 *       ) : upload?.isUploading ? (
 *         <p>Uploading... {upload.state.progress}%</p>
 *       ) : (
 *         <p>Drag a file here or click to select</p>
 *       )}
 *
 *       {dragDrop.state.errors.length > 0 && (
 *         <div style={{ color: 'red' }}>
 *           {dragDrop.state.errors.map((error, index) => (
 *             <p key={index}>{error}</p>
 *           ))}
 *         </div>
 *       )}
 *
 *       <input {...dragDrop.inputProps} />
 *     </div>
 *   )}
 * </UploadZone>
 * ```
 */
export function UploadZone({
  children,
  multiple = true,
  multiUploadOptions = {},
  uploadOptions = {},
  onUploadStart,
  onValidationError,
  ...dragDropOptions
}: UploadZoneProps) {
  // Always initialize both hooks, but only use the appropriate one
  const singleUpload = useUpload(uploadOptions);
  const multiUpload = useMultiUpload(multiUploadOptions);

  // Enhanced validation function for better error handling
  const enhancedValidator = useCallback(
    (files: File[]): string[] | null => {
      const errors: string[] = [];

      // Check file count based on multiple setting
      if (!multiple && files.length > 1) {
        errors.push(
          `Single file mode is enabled. Please select only one file. You selected ${files.length} files.`,
        );
      }

      // Enhanced MIME type validation with better error messages
      if (dragDropOptions.accept && dragDropOptions.accept.length > 0) {
        const invalidFiles = files.filter((file) => {
          return !dragDropOptions.accept?.some((acceptType) => {
            if (acceptType.startsWith(".")) {
              // File extension check
              return file.name.toLowerCase().endsWith(acceptType.toLowerCase());
            } else {
              // MIME type check (supports wildcards like image/*)
              if (acceptType.endsWith("/*")) {
                const baseType = acceptType.slice(0, -2);
                return file.type.startsWith(baseType);
              } else {
                return file.type === acceptType;
              }
            }
          });
        });

        if (invalidFiles.length > 0) {
          const fileNames = invalidFiles
            .map((f) => `"${f.name}" (${f.type})`)
            .join(", ");
          const acceptedTypes = dragDropOptions.accept.join(", ");
          errors.push(
            `Invalid file type(s): ${fileNames}. Accepted types: ${acceptedTypes}.`,
          );
        }
      }

      return errors.length > 0 ? errors : null;
    },
    [multiple, dragDropOptions.accept],
  );

  // Handle file processing
  const handleFilesReceived = (files: File[]) => {
    onUploadStart?.(files);

    if (multiple && multiUpload) {
      // Add files to multi-upload queue
      multiUpload.addFiles(files);

      // Auto-start uploads if configured to do so
      // Note: This could be made configurable with an autoStart prop
      setTimeout(() => multiUpload.startAll(), 0);
    } else if (!multiple && singleUpload && files.length > 0 && files[0]) {
      // Start single file upload
      singleUpload.upload(files[0]);
    }
  };

  // Handle validation errors
  const handleValidationError = useCallback(
    (errors: string[]) => {
      console.error("Upload zone validation errors:", errors);
      // Call the custom error handler if provided
      onValidationError?.(errors);
    },
    [onValidationError],
  );

  // Initialize drag and drop with enhanced validation
  const dragDrop = useDragDrop({
    ...dragDropOptions,
    multiple,
    validator: enhancedValidator,
    onFilesReceived: handleFilesReceived,
    onValidationError: handleValidationError,
  });

  // Determine active state
  const isActive = dragDrop.state.isDragging || dragDrop.state.isOver;

  // Determine processing state
  const isProcessing = multiple
    ? (multiUpload?.state.isUploading ?? false)
    : (singleUpload?.isUploading ?? false);

  // Create render props object
  const renderProps: UploadZoneRenderProps = {
    dragDrop,
    upload: singleUpload,
    multiUpload,
    openFilePicker: dragDrop.openFilePicker,
    isActive,
    isProcessing,
  };

  return <>{children(renderProps)}</>;
}

/**
 * Simple upload zone with built-in styling and basic functionality.
 * Provides a ready-to-use upload interface with minimal configuration.
 * Includes built-in error display for validation errors.
 *
 * @example
 * ```tsx
 * <SimpleUploadZone
 *   multiple={true}
 *   accept={['image/*']}
 *   onUploadStart={(files) => console.log('Starting uploads:', files.length)}
 *   onValidationError={(errors) => console.error('Validation errors:', errors)}
 *   multiUploadOptions={{
 *     onComplete: (results) => console.log('All uploads complete:', results),
 *   }}
 *   style={{
 *     width: '400px',
 *     height: '200px',
 *     margin: '20px auto'
 *   }}
 *   errorStyle={{
 *     backgroundColor: '#fff3cd',
 *     borderColor: '#ffeaa7'
 *   }}
 * />
 * ```
 */
export interface SimpleUploadZoneProps extends UploadZoneProps {
  /**
   * Additional CSS class name for styling
   */
  className?: string;

  /**
   * Inline styles for the upload zone
   */
  style?: React.CSSProperties;

  /**
   * Custom text to display in different states
   */
  text?: {
    idle?: string;
    dragging?: string;
    uploading?: string;
  };

  /**
   * Custom error message styling
   */
  errorStyle?: React.CSSProperties;
}

export function SimpleUploadZone({
  className = "",
  style = {},
  text = {},
  errorStyle = {},
  children,
  ...uploadZoneProps
}: SimpleUploadZoneProps) {
  const defaultText = {
    idle: uploadZoneProps.multiple
      ? "Drag files here or click to select"
      : "Drag a file here or click to select",
    dragging: uploadZoneProps.multiple
      ? "Drop files here..."
      : "Drop file here...",
    uploading: "Uploading...",
  };

  const displayText = { ...defaultText, ...text };

  // If children render prop is provided, use UploadZone directly
  if (children) {
    return <UploadZone {...uploadZoneProps}>{children}</UploadZone>;
  }

  // Otherwise, provide default UI
  return (
    <UploadZone {...uploadZoneProps}>
      {({
        dragDrop,
        upload,
        multiUpload,
        openFilePicker,
        isActive,
        isProcessing,
      }) => (
        <button
          type="button"
          onKeyDown={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              openFilePicker();
            }
          }}
          onKeyUp={(e) => {
            if (e.key === "Enter" || e.key === " ") {
              openFilePicker();
            }
          }}
          {...dragDrop.dragHandlers}
          onClick={openFilePicker}
          className={`upload-zone ${isActive ? "upload-zone--active" : ""} ${isProcessing ? "upload-zone--processing" : ""} ${className}`}
          style={{
            border: isActive ? "2px dashed #007bff" : "2px dashed #ccc",
            borderRadius: "8px",
            padding: "2rem",
            textAlign: "center",
            cursor: "pointer",
            backgroundColor: isActive ? "#f8f9fa" : "transparent",
            transition: "all 0.2s ease",
            minHeight: "120px",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            ...style,
          }}
        >
          {dragDrop.state.isDragging ? (
            <p style={{ margin: 0, fontSize: "16px", color: "#007bff" }}>
              {displayText.dragging}
            </p>
          ) : isProcessing ? (
            <div style={{ textAlign: "center" }}>
              <p style={{ margin: "0 0 10px 0", fontSize: "14px" }}>
                {displayText.uploading}
              </p>
              {upload && (
                <div>
                  <progress
                    value={upload.state.progress}
                    max={100}
                    style={{ width: "200px", height: "8px" }}
                  />
                  <p
                    style={{
                      margin: "5px 0 0 0",
                      fontSize: "12px",
                      color: "#666",
                    }}
                  >
                    {upload.state.progress}%
                  </p>
                </div>
              )}
              {multiUpload && (
                <div>
                  <progress
                    value={multiUpload.state.progress}
                    max={100}
                    style={{ width: "200px", height: "8px" }}
                  />
                  <p
                    style={{
                      margin: "5px 0 0 0",
                      fontSize: "12px",
                      color: "#666",
                    }}
                  >
                    {multiUpload.state.progress}% ({multiUpload.state.uploading}{" "}
                    uploading, {multiUpload.state.successful} completed)
                  </p>
                </div>
              )}
            </div>
          ) : (
            <p style={{ margin: 0, fontSize: "16px", color: "#666" }}>
              {displayText.idle}
            </p>
          )}

          {dragDrop.state.errors.length > 0 && (
            <div
              style={{
                marginTop: "10px",
                padding: "8px 12px",
                backgroundColor: "#f8d7da",
                border: "1px solid #f5c6cb",
                borderRadius: "4px",
                maxWidth: "100%",
                ...errorStyle,
              }}
            >
              <p
                style={{
                  margin: "0 0 5px 0",
                  fontSize: "12px",
                  fontWeight: "bold",
                  color: "#721c24",
                }}
              >
                Validation Errors:
              </p>
              {dragDrop.state.errors.map((error, index) => (
                <p
                  // biome-ignore lint/suspicious/noArrayIndexKey: index is used as key
                  key={index}
                  style={{
                    color: "#721c24",
                    fontSize: "11px",
                    margin: "2px 0",
                    lineHeight: "1.3",
                  }}
                >
                  • {error}
                </p>
              ))}
            </div>
          )}

          <input {...dragDrop.inputProps} />
        </button>
      )}
    </UploadZone>
  );
}
